services:
  
  nginx-rev-pxy-srv:
    container_name: m5-ble_nginx
    build:
      context: ./services/nginx-rev-pxy/
      dockerfile: Dockerfile
    volumes:
        - ./services/nginx-rev-pxy/default.conf:/etc/nginx/conf.d/default.conf # nginxの全般設定
        - ./services/nginx-rev-pxy/ssl/:/etc/nginx/ssl/ # ssl keys
        - ./services/nginx-rev-pxy/statics:/etc/nginx/static/statics # static
    ports: # ホストマシンのポートとコンテナのポートをマッピング 
      # - 80:80 # httpアクセス用のポート
      - "${REV_PXY_HTTPS_HOST_PORT:-443}:443"
    restart: always
    tty: true
